// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftTrackingApp.Data;

#nullable disable

namespace ShiftTrackingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520031646_AddCasualCallouts")]
    partial class AddCasualCallouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftTrackingApp.Models.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.CasualCallout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalledUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("CalledUserId", "Status");

                    b.ToTable("CasualCallouts");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kumaş kesim hattı",
                            Name = "Kesim"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dikiş atölyesi (en kalabalık bölüm)",
                            Name = "Dikiş"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ütüleme ve paketleme bandı",
                            Name = "Ütü & Paketleme"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ürün kalite muayene",
                            Name = "Kalite Kontrol"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Depo / sevkiyat hattı",
                            Name = "Sevkiyat"
                        });
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.FaceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedDescriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FaceData");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DocumentBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("HasMedicalReport")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.OvertimeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#f59e0b",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Name = "Sabah",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4f6ef7",
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Öğleden Sonra",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#a78bfa",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            Name = "Gece",
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ef4444",
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Tatil",
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#22c55e",
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "İzinli",
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Color = "#14b8a6",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            Name = "Part Time",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Color = "#f97316",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            Name = "Sabah Fazla Mesai",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6366f1",
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Öğleden Sonra Fazla Mesai",
                            StartTime = new TimeSpan(0, 22, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Color = "#ec4899",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            Name = "Gece Fazla Mesai",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId", "Date", "ShiftId")
                        .IsUnique();

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.ShiftSwapRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DesiredShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("RequesterShiftAssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetShiftAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesiredShiftId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("RequesterShiftAssignmentId");

                    b.HasIndex("TargetShiftAssignmentId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("ShiftSwapRequests");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.StaffingRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("DepartmentId", "ShiftId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("StaffingRequirements");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Ayşe Yılmaz",
                            HireDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$E.YPlfQB/vm9Ef/cni.wROw1JGbmwwGVCWe7WI4LWCxMY0fjZYNnu",
                            Position = "Üretim Müdürü",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "mehmet@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Mehmet Kaya",
                            HireDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$wfZHxZ2X.NMhZdirV1rJDO6FR6svu2Ll9MnlWG5Nbl.T4.1AYtmLG",
                            Position = "Dikiş Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "hasan.demir@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Hasan Demir",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Kesim",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "murat.aksoy@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Murat Aksoy",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Kesim",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "fatma.sahin@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Fatma Şahin",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Dikiş",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "zeynep.aydin@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Zeynep Aydın",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Dikiş",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "emine.celik@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Emine Çelik",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Dikiş",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "sibel.polat@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Sibel Polat",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Ütü & Paketleme",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "burak.ozturk@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Burak Öztürk",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Kalite Kontrol",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "selim.kurt@shifttrack.com",
                            EmploymentType = "Casual",
                            FullName = "Selim Kurt",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$OtjPXY5sSdMc2Sagr6O8r.5j0a8vAlJROTuKr03GvMsmhL/G2P3Li",
                            Position = "Yevmiyeci · Sevkiyat",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ali.vural@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Ali Vural",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kesim Ustası",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "cemal.dogan@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Cemal Doğan",
                            HireDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kesim Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "hakan.arslan@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Hakan Arslan",
                            HireDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kesim Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "osman.yildirim@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Osman Yıldırım",
                            HireDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kesim Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "elif.simsek@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Elif Şimşek",
                            HireDate = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Dikiş Ustası",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "derya.koc@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Derya Koç",
                            HireDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Dikiş Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "gul.erdogan@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Gül Erdoğan",
                            HireDate = new DateTime(2022, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Overlok Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "hatice.aslan@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Hatice Aslan",
                            HireDate = new DateTime(2022, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Dikiş Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "meryem.tas@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Meryem Taş",
                            HireDate = new DateTime(2023, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Dikiş Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "nurten.acar@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Nurten Acar",
                            HireDate = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Düğme/İlik Operatörü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "kemal.sen@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Kemal Şen",
                            HireDate = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Ütü Ustası",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "ramazan.bulut@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Ramazan Bulut",
                            HireDate = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Ütücü",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "yasemin.toprak@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Yasemin Toprak",
                            HireDate = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Paketleme Elemanı",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "hulya.cetin@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Hülya Çetin",
                            HireDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Paketleme Elemanı",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "serkan.korkmaz@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Serkan Korkmaz",
                            HireDate = new DateTime(2020, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kalite Şefi",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "aylin.gunes@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Aylin Güneş",
                            HireDate = new DateTime(2022, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kalite Kontrolör",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "pinar.yalcin@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Pınar Yalçın",
                            HireDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Kalite Kontrolör",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "tolga.eren@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Tolga Eren",
                            HireDate = new DateTime(2021, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Sevkiyat Sorumlusu",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "erhan.avci@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Erhan Avcı",
                            HireDate = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Depo Görevlisi",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "volkan.kaplan@shifttrack.com",
                            EmploymentType = "Permanent",
                            FullName = "Volkan Kaplan",
                            HireDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$TVb1Y7cHcpUJlrAQLLs.ueVrdsfZuPRbUOSYI7o2KTYtTgOqzDfhS",
                            Position = "Depo Görevlisi",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.AttendanceLog", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.CasualCallout", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.User", "CalledUser")
                        .WithMany()
                        .HasForeignKey("CalledUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalledUser");

                    b.Navigation("Department");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.FaceData", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.LeaveRequest", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.OvertimeRequest", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.RefreshToken", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.ShiftAssignment", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.Shift", "Shift")
                        .WithMany("Assignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.User", "User")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.ShiftSwapRequest", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.Shift", "DesiredShift")
                        .WithMany()
                        .HasForeignKey("DesiredShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftTrackingApp.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.ShiftAssignment", "RequesterShiftAssignment")
                        .WithMany()
                        .HasForeignKey("RequesterShiftAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.ShiftAssignment", "TargetShiftAssignment")
                        .WithMany()
                        .HasForeignKey("TargetShiftAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftTrackingApp.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DesiredShift");

                    b.Navigation("Requester");

                    b.Navigation("RequesterShiftAssignment");

                    b.Navigation("TargetShiftAssignment");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.StaffingRequirement", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftTrackingApp.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.User", b =>
                {
                    b.HasOne("ShiftTrackingApp.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.Shift", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ShiftTrackingApp.Models.User", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("LeaveRequests");

                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
